### ISSUE TITLE
Version V1.1.0.0 problem

### ISSUE THREAD

**Issue by SquireAu02** [BdcashProtocol/bdcashprotocol-bdeco#8]
after installing the new wallet, I only have one connection with both windows and vps wallets are not in sync with the BdcashProtocol Block Explorer. masternodes do not start!
Please publish addnodes and a bootstrap for V1.1.00 wallet

**Comment by bdcashdev** [comment]
more details go to discord server project ;)

**Comment by SquireAu02** [comment]
not sure if this is related to the previous issue but I can get a output when I type getmasternodeoutputs?

13:56:12
￼
getmasternodeoutputs


13:56:12
￼
[
]
the wallet is synced already, block 76503 currently the same as the explorer

**Comment by bdcashdev** [comment]
Checking this issue

**Comment by bdcashdev** [comment]
Fidex #10
